Repository eptastellar/Orbit, pull requests merged in 2024-06, with the labels that each got.

#49 ReadMe and .github
  .github/CODEOWNERS
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/jest_unit_testing.yml
  README.md
  app/package.json
  app/pnpm-lock.yaml
Labels: documentation, actions

#54 Comments, privacy policy, supernova and requests bump to nestjs arch
  app/package.json
  app/pnpm-lock.yaml
  app/src/app/(app)/new-post/page.tsx
  app/src/app/(app)/notifications/requests.ts
  app/src/app/(app)/p/[post]/page.tsx
  app/src/app/(app)/p/[post]/requests.ts
  app/src/app/(app)/qr/code/requests.ts
  app/src/app/(app)/requests.ts
  app/src/app/(app)/settings/page.tsx
  app/src/app/(app)/supernova/accepted/page.tsx
  app/src/app/(app)/supernova/page.tsx
  app/src/app/(app)/supernova/refused/page.tsx
  app/src/app/(app)/supernova/rejected/page.tsx
  app/src/app/(app)/u/[username]/requests.ts
  app/src/app/favicon.ico
  app/src/app/globals.css
  app/src/app/icon.png
  app/src/app/manifest.ts
  app/src/app/onboarding/(authentication)/page.tsx
  app/src/app/onboarding/(authentication)/sign-in/page.tsx
  app/src/app/onboarding/(profile-creation)/interests/page.tsx
  app/src/app/onboarding/(profile-creation)/profile/page.tsx
  app/src/app/privacy-policy/page.tsx
  app/src/assets/brand/black/1024.png
  app/src/assets/brand/black/128.png
  app/src/assets/brand/black/256.png
  app/src/assets/brand/black/512.png
  app/src/assets/brand/black/64.png
  app/src/assets/brand/icon-round.png
  app/src/assets/brand/icon.png
  app/src/assets/brand/white/1024.png
  app/src/assets/brand/white/128.png
  app/src/assets/brand/white/256.png
  app/src/assets/brand/white/512.png
  app/src/assets/brand/white/64.png
  app/src/assets/galaxy.png
  app/src/assets/icons/CaretDown.tsx
  app/src/assets/icons/PaperPlaneUp.tsx
  app/src/assets/icons/RepliedRight.tsx
  app/src/assets/icons/ReplyLeft.tsx
  app/src/assets/icons/index.ts
  app/src/assets/index.ts
  app/src/components/comment/Comment.tsx
  app/src/components/comment/NewComment.tsx
  app/src/components/index.ts
  app/src/components/navigation/Header.tsx
  app/src/types/index.ts
Labels: enhancement, frontend, dependencies

#55 Post text fix
  app/src/app/(app)/p/[post]/requests.ts
  app/src/app/(app)/requests.ts
  app/src/app/(app)/u/[username]/requests.ts
Labels: bug, frontend

#59 Supernova fix
  web/src/handlers/supernova/supernova.controller.ts
  web/src/handlers/supernova/supernova.service.ts
Labels: bug, backend
