Repository eptastellar/Orbit, pull requests merged in 2024-04, with the labels that each got.

#23 Infrastructure gitignore update
  .gitignore
  app/.gitignore
  docs/StackChart.svg
  docs/SupernovaFunctionality.drawio.svg
  docs/organization_chart.svg
  web/.gitignore
  web/package.json
Labels: enhancement

#30 Frontend code review
  app/.eslintrc.js
  app/next.config.js
  app/package.json
  app/pnpm-lock.yaml
  app/src/app/(app)/layout.tsx
  app/src/app/(app)/page.tsx
  app/src/app/(app)/requests.ts
  app/src/app/(app)/settings/page.tsx
  app/src/app/(app)/settings/update-password/page.tsx
  app/src/app/(app)/u/[username]/page.tsx
  app/src/app/(app)/u/[username]/requests.ts
  app/src/app/globals.css
  app/src/app/layout.tsx
  app/src/app/not-found.tsx
  app/src/app/onboarding/(authentication)/forgot-password/page.tsx
  app/src/app/onboarding/(authentication)/layout.tsx
  app/src/app/onboarding/(authentication)/page.tsx
  app/src/app/onboarding/(authentication)/sign-in/page.tsx
  app/src/app/onboarding/(authentication)/sign-up/page.tsx
  app/src/app/onboarding/(profile-creation)/interests/page.tsx
  app/src/app/onboarding/(profile-creation)/layout.tsx
  app/src/app/onboarding/(profile-creation)/profile/page.tsx
  app/src/app/onboarding/layout.tsx
  app/src/app/onboarding/verification/layout.tsx
  app/src/app/onboarding/verification/page.tsx
  app/src/assets/icons/Cross.tsx
  app/src/assets/icons/index.ts
  app/src/assets/illustrations/password-update.svg
  app/src/assets/illustrations/rotate-device.svg
  app/src/assets/index.ts
  app/src/components/button/BackButton.tsx
  app/src/components/button/InterestButton.tsx
  app/src/components/button/LargeButton.tsx
  app/src/components/button/SettingsButton.tsx
  app/src/components/button/WelcomeButton.tsx
  app/src/components/index.ts
  app/src/components/input/FullInput.tsx
  app/src/components/input/Input.tsx
  app/src/components/loading/InfiniteLoader.tsx
  app/src/components/loading/LoadingOverlay.tsx
  app/src/components/loading/SpinnerText.tsx
  app/src/components/navigation/Header.tsx
  app/src/components/navigation/HeaderWithButton.tsx
  app/src/components/navigation/Navbar.tsx
  app/src/components/popup/FloatingConfirmation.tsx
  app/src/components/post/AudioEmbed.tsx
  app/src/components/post/Post.tsx
  app/src/contexts/AuthContext.tsx
  app/src/contexts/Providers.tsx
  app/src/contexts/UserContext.tsx
  app/src/hooks/useIsInViewport.ts
  app/src/libraries/firebaseErrors.ts
  app/src/types/index.ts
  app/tailwind.config.ts
Labels: enhancement, frontend, dependencies

#31 Backend refactoring & Supernova fixes
  .github/dependabot.yml
  .gitignore
  web/.eslintrc.json
  web/jest.config.js
  web/package.json
  web/pnpm-lock.yaml
  web/src/algorithms/__mocks__/index.spec.ts
  web/src/algorithms/index.ts
  web/src/algorithms/supernova.ts
  web/src/assets/content/interests.ts
  web/src/assets/index.ts
  web/src/config/index.ts
  web/src/config/neo4j.config.ts
  web/src/contexts/AuthContext.ts
  web/src/contexts/ContentContext.ts
  web/src/contexts/CronJobsContext.ts
  web/src/contexts/UserContext.ts
  web/src/contexts/ValidationContext.ts
  web/src/routes/auth/log-out/index.ts
  web/src/routes/auth/sign-in/index.ts
  web/src/routes/auth/sign-up/index.ts
  web/src/routes/auth/sign-up/validate/index.ts
  web/src/routes/c/[id].ts
  web/src/routes/c/leafs/[id].ts
  web/src/routes/c/roots/[id].ts
  web/src/routes/cron/keep-alive-neo4j/index.ts
  web/src/routes/home/messages/index.ts
  web/src/routes/home/posts/index.ts
  web/src/routes/index.ts
  web/src/routes/interests/index.ts
  web/src/routes/l/[id].ts
  web/src/routes/p/[id].ts
  web/src/routes/p/index.ts
  web/src/routes/u/[username].ts
  web/src/routes/u/posts/[username].ts
  web/src/routes/u/qr/index.ts
  web/src/routes/u/settings/index.ts
  web/src/services/AuthService.ts
  web/src/services/ContentService.ts
  web/src/services/CronJobsService.ts
  web/src/services/UserService.ts
  web/src/services/ValidationService.ts
  web/src/services/index.ts
  web/src/types/index.ts
  web/tsconfig.json
Labels: enhancement, backend

#34 Jest configuration
  .github/workflows/jest_unit_testing.yml
  web/src/algorithms/__mocks__/index.spec.ts
  web/src/algorithms/supernova.ts
  web/src/config/index.ts
  web/src/config/neo4j.config.ts
Labels: backend, actions

#37 GitHub actions
  .github/workflows/jest_unit_testing.yml
  web/package.json
  web/pnpm-lock.yaml
Labels: enhancement, actions, dependencies
